server:
  port: 8080

mybatis:
  config-location: classpath:mybatis/mybatis-cfg.cml
  type-aliases-package: cn.hassan.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: service-provider
    datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
      url: jdbc:mysql://47.99.217.209:3306/cloud              # 数据库名称
      username: root
      password: 123456
      dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        initial-size: 5                                       # 初始化连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200                                  # 等待连接获取的最大超时时间