server:
  port: 7002
eureka:
  instance:
    hostname: eureka02.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetch-registry: false #false 表示自己端是注册中心，职责是维护服务实例，不是去检索服务
    service-url:
      defaultZone: http://eureka01.com:7001/eureka/
